spring:
  application:
    name: uaa
  boot:
    admin:
      client:
        url: http://localhost:7003
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://192.168.3.169:3306/uaa_srv?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 180000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 # 连接池最大连接数，默认是10
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: uaa-hikaricp
      connection-test-query: SELECT 1
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      dialect: org.hibernate.dialec.MySQL8Dialect
  thymeleaf:
    cache: false
    prefix: classpath:/views/
    mode: HTML
  redis:
    database: 0
    host: 192.168.3.169
    port: 6379

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        requestInterceptors:
          - cn.metaq.fegin.authz.interceptor.FeignClientsRequestInterceptor


security:
  oauth2:
    client:
      authentication-scheme: header
      client-authentication-scheme: header

server:
  port: 8001
  servlet:
    context-path: /auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

debug: true