spring:
  application:
    name: uaa
  boot:
    admin:
      client:
        url: http://192.168.3.189:5100
  cache:
    type: redis
  thymeleaf:
    cache: false
    prefix: classpath:/views/
    mode: HTML
  redis:
    database: 0
    host: 192.168.3.189
    port: 6379
  data:
    mongodb:
      host: 192.168.3.189
      port: 27017
      database: sessionmgmt

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        requestInterceptors:
          - cn.metaq.fegin.authz.interceptor.FeignClientsRequestInterceptor


security:
  oauth2:
    client:
      authentication-scheme: header
      client-authentication-scheme: header

server:
  port: 8001
  servlet:
    context-path: /auth

eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.189:5001/eureka/,http://192.168.3.189:5002/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#debug: true