feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        requestInterceptors:
          - cn.metaq.fegin.authz.interceptor.FeignClientsRequestInterceptor
