spring:
  application:
    name: uaa-srv

  redis:
    database: 0
    host: uaa.metaq.cn
    port: 6379

  datasource:
    url: jdbc:mysql://uaa.metaq.cn:13306/uaa_srv?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 180000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 # 连接池最大连接数，默认是10
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: uaa-hikaricp
      connection-test-query: SELECT 1
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 10004

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        requestInterceptors:
#          - cn.metaq.fegin.authz.interceptor.FeignClientsRequestInterceptor
#
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8001/auth/current
    #      prefer-token-info: false
    client:
      client-id: clientdetails
      client-secret: $2a$10$xR9gilJBvsJpyggPgpYNve/8LoZUbXORtWSLmDF8yOaqu0C043a76
      access-token-uri: http://localhost:8001/auth/oauth/token
      user-authorization-uri: http://localhost:8001/auth/oauth/authorize

debug: true