spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: uaa
          uri: lb://uaa
          predicates:
            - Path= /uaa/**
          filters:
            - StripPrefix=1
        - id: area-srv
          uri: lb://area-srv
          predicates:
            - Path= /area/**
          filters:
            - StripPrefix=1
server:
  port: 7002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
