spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: uaa
          uri: lb://uaa
          predicates:
            - Path= /uaa/**
          filters:
            - StripPrefix=1
        - id: area-srv
          uri: lb://area-srv
          predicates:
            - Path= /common/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                # 令牌桶每秒填充平均速率, 允许用户每秒处理多少个请求。
                redis-rate-limiter.replenishRate: 2
                # 令牌桶的容量，允许在1s内完成的最大请求数。
                redis-rate-limiter.burstCapacity: 20
                # 使用SpEL表达式从Spring容器中获取Bean对象, 查看RateLimiteConfig实现类中的同名方法
                key-resolver: "#{@hostKeyResolver}"
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/default/fallback
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
server:
  port: 7002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true


# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true
